### ISSUE TITLE
Spring Boot Update 2.0.0 M4

### ISSUE THREAD

**Issue by evainga** [evainga/rememberbrall#2]

**Comment by evainga** [comment]
still problematic... eclipse says: 

> Could not resolve artifact org.springframework.boot:spring-boot-dependencies:pom:2.0.0.M4
> Missing org.springframework.boot:spring-boot-dependencies:pom:2.0.0.M4

and in command line after mvn clean verify

> createEntry(de.rememberbrall.RememberbrallDocumentation)  Time elapsed: 0.027 sec  <<< FAILURE!
> java.lang.NoClassDefFoundError: groovy/lang/GroovyInterceptable at de.rememberbrall.RememberbrallDocumentation.getPlainRequestSpec(RememberbrallDocumentation.java:48)
> at de.rememberbrall.RememberbrallDocumentation.createEntry(RememberbrallDocumentation.java:98)
> Caused by: java.lang.ClassNotFoundException: groovy.lang.GroovyInterceptable at de.rememberbrall.RememberbrallDocumentation.getPlainRequestSpec(RememberbrallDocumentation.java:48) at de.rememberbrall.RememberbrallDocumentation.createEntry(RememberbrallDocumentation.java:98)

**Comment by evainga** [comment]
here it is: https://github.com/evainga/rememberbrall/tree/update-spring-boot

**Comment by evainga** [comment]
mvn clean verify is working now, only eclipse is still not happy - I will have to accept that for the start
